version: "2"
services:
  kaws:
{% include 'templates/docker-compose-service.yml.j2' %}
    ports:
      - 4000:4000
    env_file: ../.env
    environment:
      - MONGOHQ_URL=mongodb://kaws-mongodb:27017/kaws
    depends_on:
      - kaws-mongodb
  kaws-mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"
    command: ["--storageEngine=mmapv1", "--quiet", "--nojournal"]
