apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kaws-web
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kaws
        component: web
        layer: application
      name: kaws-web
    spec:
      containers:
        - name: kaws-web
          env:
            - name: PORT
              value: "8080"
            - name: DD_TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_OPTIONS
              value: "--max_old_space_size=256"
          envFrom:
            - configMapRef:
                name: kaws-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/kaws:staging
          imagePullPolicy: Always
          ports:
            - name: kaws-http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              port: kaws-http
              path: /health
              httpHeaders:
                - name: X-FORWARDED-PROTO
                  value: https
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - foreground

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kaws-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: kaws-web
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kaws
    component: web
    layer: application
  name: kaws-web-internal
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: 8080
  selector:
    app: kaws
    layer: application
    component: web
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kaws
  annotations:
    kubernetes.io/ingress.class: nginx-internal
spec:
  rules:
    - host: kaws.stg.artsy.systems
      http:
        paths:
          - path: /
            backend:
              serviceName: kaws-web-internal
              servicePort: http

---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: kaws-update-sailthu
spec:
  schedule: 13 13 * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - name: kaws-update-sailthru
              image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/kaws:staging
              args:
                - "yarn"
                - "run"
                - "update-sailthru"
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: kaws-environment
          restartPolicy: Never
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: tier
                        operator: In
                        values:
                          - background

---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: kaws-update-elastic-search
spec:
  schedule: 7 15 * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - name: kaws-update-elastic-search
              image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/kaws:staging
              args:
                - "yarn"
                - "run"
                - "index-for-search"
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: kaws-environment
          restartPolicy: Never
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: tier
                        operator: In
                        values:
                          - background

---
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: kaws-update-price-guidance
spec:
  schedule: 0 13 * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - name: kaws-update-price-guidance
              image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/kaws:production
              args:
                - "yarn"
                - "run"
                - "update-price-guidance"
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: kaws-environment
          restartPolicy: Never
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: tier
                        operator: In
                        values:
                          - background

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kaws-data-import
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: kaws-data-import-cron
              image: artsy/mongo-data-sync
              imagePullPolicy: Always
              env:
                - name: APP_NAME
                  value: "kaws"
              envFrom:
                - configMapRef:
                    name: kaws-environment
              args: ["sh", "./import-db.sh", "production"]
          restartPolicy: Never
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: tier
                        operator: In
                        values:
                          - background
